spring:
  application:
    name: springboot
  flyway:
    locations: classpath:/db/migration/postgresql
    schemas: institution
    baselineOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pez
  security:
    jwt:
      token:
        secret-key: "633e77f1fd802aa153209d405ab76b8d5f900e7354c3a220a8941263b0a5fc3b"
