
CREATE TABLE achievement_levels
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255),
    description         TEXT,
    score               INTEGER                                 NOT NULL,
    rubric_criterion_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_achievement_levels PRIMARY KEY (id)
);

CREATE TABLE assessment_students
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    score              DOUBLE PRECISION                        NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    feedback           TEXT,
    student_id         BIGINT                                  NOT NULL,
    assessment_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_assessment_students PRIMARY KEY (id)
);

CREATE TABLE assessments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255),
    type               VARCHAR(255)                            NOT NULL,
    percentage         DOUBLE PRECISION                        NOT NULL,
    total_points       DOUBLE PRECISION                        NOT NULL,
    assessment_date    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    course_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_assessments PRIMARY KEY (id)
);

CREATE TABLE attendance_students
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    status             VARCHAR(255)                            NOT NULL,
    justification      TEXT,
    student_id         BIGINT,
    attendance_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_attendance_students PRIMARY KEY (id)
);

CREATE TABLE attendances
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    class_occurred     BOOLEAN                                 NOT NULL,
    course_id          BIGINT                                  NOT NULL,
    comment            TEXT,
    date_of_class      date                                    NOT NULL,
    CONSTRAINT pk_attendances PRIMARY KEY (id)
);

CREATE TABLE course_student
(
    course_id  BIGINT NOT NULL,
    student_id BIGINT NOT NULL
);

CREATE TABLE courses
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255),
    instructor_id      BIGINT                                  NOT NULL,
    type               VARCHAR(255)                            NOT NULL,
    start_date         TIMESTAMP WITHOUT TIME ZONE,
    end_date           TIMESTAMP WITHOUT TIME ZONE,
    max_capacity       INTEGER                                 NOT NULL,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE evaluation_rubrics
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    assessment_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_evaluation_rubrics PRIMARY KEY (id)
);

CREATE TABLE rubric_criterion
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                VARCHAR(255),
    evaluation_rubric_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_rubric_criterion PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dtype                     VARCHAR(31),
    created_by                VARCHAR(255),
    created_date              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by          VARCHAR(255),
    last_modified_date        TIMESTAMP WITHOUT TIME ZONE,
    name                      VARCHAR(255),
    last_name                 VARCHAR(255),
    email                     VARCHAR(255),
    password                  VARCHAR(255),
    role                      VARCHAR(255)                            NOT NULL,
    has_curricular_adaptation BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE evaluation_rubrics
    ADD CONSTRAINT uc_evaluation_rubrics_assessment UNIQUE (assessment_id);

ALTER TABLE achievement_levels
    ADD CONSTRAINT FK_ACHIEVEMENT_LEVELS_ON_RUBRIC_CRITERION FOREIGN KEY (rubric_criterion_id) REFERENCES rubric_criterion (id);

ALTER TABLE assessments
    ADD CONSTRAINT FK_ASSESSMENTS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE assessment_students
    ADD CONSTRAINT FK_ASSESSMENT_STUDENTS_ON_ASSESSMENT FOREIGN KEY (assessment_id) REFERENCES assessments (id);

ALTER TABLE assessment_students
    ADD CONSTRAINT FK_ASSESSMENT_STUDENTS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES users (id);

ALTER TABLE attendances
    ADD CONSTRAINT FK_ATTENDANCES_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE attendance_students
    ADD CONSTRAINT FK_ATTENDANCE_STUDENTS_ON_ATTENDANCE FOREIGN KEY (attendance_id) REFERENCES attendances (id);

ALTER TABLE attendance_students
    ADD CONSTRAINT FK_ATTENDANCE_STUDENTS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES users (id);

ALTER TABLE courses
    ADD CONSTRAINT FK_COURSES_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES users (id);

ALTER TABLE evaluation_rubrics
    ADD CONSTRAINT FK_EVALUATION_RUBRICS_ON_ASSESSMENT FOREIGN KEY (assessment_id) REFERENCES assessments (id);

ALTER TABLE rubric_criterion
    ADD CONSTRAINT FK_RUBRIC_CRITERION_ON_EVALUATION_RUBRIC FOREIGN KEY (evaluation_rubric_id) REFERENCES evaluation_rubrics (id);

ALTER TABLE course_student
    ADD CONSTRAINT fk_coustu_on_course FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE course_student
    ADD CONSTRAINT fk_coustu_on_student FOREIGN KEY (student_id) REFERENCES users (id);